# Generated by Django 4.1.4 on 2023-04-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
