# Generated by Django 4.1.4 on 2023-04-18 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0004_remove_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='thematic',
            field=models.CharField(choices=[('GS', 'СВЕТСКИЕ НОВОСТИ'), ('PO', 'ПОЛИТИКА'), ('TH', 'ТЕХНИКА'), ('BL', 'СРОЧНЫЕ НОВОСТИ')], default='gossip', max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_choice',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], default='NE', max_length=2),
        ),
    ]
